name: stylelint-config-npm-publish

on:
  push:
    branches:
      - main
    paths:
      - stylelint-config/package.json

defaults:
  run:
    working-directory: stylelint-config
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@day1co"
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm ci
          npm publish
